### ISSUE TITLE
panic decoding packet

### ISSUE THREAD

**Issue by blalor** [siddontang/go-mysql#12]
I'm in pretty deep over my head here, but in attempting to write a simple program that dumps replication events from one of my MySQL 5.6.20 servers (based on the example in the README), I'm getting a panic in `parser.go`.  Here's a test that reproduces the problem, but I had to build up `parser.format` and `parser.tables` from the `parser` state just before my program crashes.  It's possible that earlier events are the true cause of the problem, but I do feel like an index bounds check in [`RowsEvent.decodeRows`](https://github.com/siddontang/go-mysql/blob/1fcd9ccb92570c556a5585320627deb561069297/replication/row_event.go#L292) would help avoid the panic.

Here's `parser_test.go`:
```
package replication

import (
	"testing"
)

func TestIndexOutOfRange(t *testing.T) {
	parser := NewBinlogParser()

	parser.format = &FormatDescriptionEvent{
		Version:                0x4,
		ServerVersion:          []uint8{0x35, 0x2e, 0x36, 0x2e, 0x32, 0x30, 0x2d, 0x6c, 0x6f, 0x67, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		CreateTimestamp:        0x0,
		EventHeaderLength:      0x13,
		EventTypeHeaderLengths: []uint8{0x38, 0xd, 0x0, 0x8, 0x0, 0x12, 0x0, 0x4, 0x4, 0x4, 0x4, 0x12, 0x0, 0x0, 0x5c, 0x0, 0x4, 0x1a, 0x8, 0x0, 0x0, 0x0, 0x8, 0x8, 0x8, 0x2, 0x0, 0x0, 0x0, 0xa, 0xa, 0xa, 0x19, 0x19, 0x0},
		ChecksumAlgorithm:      0x1,
	}
	
	parser.tables = map[uint64]*TableMapEvent{
		0x3043b:  &TableMapEvent{tableIDSize:6, TableID:0x3043b, Flags:0x1, Schema:[]uint8{0x73, 0x65, 0x69, 0x75, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72}, Table:[]uint8{0x61, 0x70, 0x70, 0x5f, 0x63, 0x72, 0x6f, 0x6e}, ColumnCount:0x15, ColumnType:[]uint8{0x3, 0xf, 0xc, 0xc, 0xf, 0x3, 0xc, 0x3, 0xfc, 0xf, 0x1, 0xfe, 0x2, 0xc, 0xf, 0xf, 0xc, 0xf, 0xf, 0x3, 0xf}, ColumnMeta:[]uint16{0x0, 0x180, 0x0, 0x0, 0x2fd, 0x0, 0x0, 0x0, 0x2, 0x180, 0x0, 0xfe78, 0x0, 0x0, 0x180, 0x180, 0x0, 0x180, 0x180, 0x0, 0x2fd}, NullBitmap:[]uint8{0xf8, 0xfb, 0x17}},
		0x30453:  &TableMapEvent{tableIDSize:6, TableID:0x30453, Flags:0x1, Schema:[]uint8{0x73, 0x65, 0x69, 0x75, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72}, Table:[]uint8{0x73, 0x74, 0x67, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70}, ColumnCount:0x36, ColumnType:[]uint8{0x3, 0x3, 0x3, 0x3, 0x3, 0xf, 0xf, 0x8, 0x3, 0x3, 0x3, 0xf, 0xf, 0x1, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xfe, 0x12, 0xf, 0xf, 0xf, 0xf6, 0x1, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xfe, 0xf6, 0x12, 0x3, 0xf, 0xf, 0x1, 0x1, 0x12, 0xf, 0xf, 0xf, 0xf, 0x3, 0xf, 0x3}, ColumnMeta:[]uint16{0x0, 0x0, 0x0, 0x0, 0x0, 0x2fd, 0x12c, 0x0, 0x0, 0x0, 0x0, 0x180, 0x180, 0x0, 0x30, 0x180, 0x180, 0x180, 0x30, 0xc0, 0xfe03, 0x0, 0x180, 0x180, 0x180, 0xc02, 0x0, 0x5a, 0x5a, 0x5a, 0x5a, 0x2fd, 0x2fd, 0x2fd, 0xc0, 0x12c, 0x30, 0xc, 0xfe06, 0xb02, 0x0, 0x0, 0x180, 0x180, 0x0, 0x0, 0x0, 0x180, 0x180, 0x2d, 0x2fd, 0x0, 0x2fd, 0x0}, NullBitmap:[]uint8{0xee, 0xdf, 0xff, 0xff, 0xff, 0xff, 0x17}},
		0x30504:  &TableMapEvent{tableIDSize:6, TableID:0x30504, Flags:0x1, Schema:[]uint8{0x73, 0x65, 0x69, 0x75, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72}, Table:[]uint8{0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x74, 0x67, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70}, ColumnCount:0x13, ColumnType:[]uint8{0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0x3, 0xf, 0xc, 0xc, 0xc, 0xf, 0xf, 0x3, 0xf}, ColumnMeta:[]uint16{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x180, 0x0, 0x0, 0x0, 0x180, 0x180, 0x0, 0x2fd}, NullBitmap:[]uint8{0x6, 0xfb, 0x5}},
		0x30450:  &TableMapEvent{tableIDSize:6, TableID:0x30450, Flags:0x1, Schema:[]uint8{0x73, 0x65, 0x69, 0x75, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72}, Table:[]uint8{0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74}, ColumnCount:0x16, ColumnType:[]uint8{0x3, 0xfc, 0xc, 0x3, 0xc, 0xf, 0x3, 0xf, 0xc, 0xf, 0xf, 0xf, 0xf, 0x3, 0xc, 0xf, 0xf, 0xf, 0xf, 0x3, 0x3, 0xf}, ColumnMeta:[]uint16{0x0, 0x2, 0x0, 0x0, 0x0, 0x2d, 0x0, 0x180, 0x0, 0x180, 0x180, 0x2fd, 0x2d, 0x0, 0x0, 0x180, 0x180, 0x2fd, 0x2d, 0x0, 0x0, 0x2fd}, NullBitmap:[]uint8{0xfe, 0xff, 0x2f}},
		0x305bb:  &TableMapEvent{tableIDSize:6, TableID:0x305bb, Flags:0x1, Schema:[]uint8{0x79, 0x6d, 0x63, 0x61, 0x63, 0x68, 0x67, 0x6f}, Table:[]uint8{0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x6c, 0x6f, 0x67}, ColumnCount:0x11, ColumnType:[]uint8{0x3, 0x3, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xc, 0xf, 0xf, 0xc, 0xf, 0xf, 0x3, 0xf}, ColumnMeta:[]uint16{0x0, 0x0, 0x2fd, 0x12c, 0x2fd, 0x2fd, 0x2d, 0x12c, 0x2fd, 0x0, 0x180, 0x180, 0x0, 0x180, 0x180, 0x0, 0x2fd}, NullBitmap:[]uint8{0xfe, 0x7f, 0x1}},
		0x16c36b: &TableMapEvent{tableIDSize:6, TableID:0x16c36b, Flags:0x1, Schema:[]uint8{0x61, 0x63, 0x70}, Table:[]uint8{0x73, 0x74, 0x67, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x32}, ColumnCount:0xe, ColumnType:[]uint8{0x8, 0x8, 0x3, 0x3, 0x2, 0x2, 0xf, 0x12, 0xf, 0xf, 0x12, 0xf, 0xf, 0xf}, ColumnMeta:[]uint16{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2d, 0x0, 0x180, 0x180, 0x0, 0x180, 0x180, 0x2fd}, NullBitmap:[]uint8{0xba, 0x3f}},
		0x16c368: &TableMapEvent{tableIDSize:6, TableID:0x16c368, Flags:0x1, Schema:[]uint8{0x73, 0x65, 0x69, 0x75, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72}, Table:[]uint8{0x73, 0x74, 0x67, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x32}, ColumnCount:0xe, ColumnType:[]uint8{0x8, 0x8, 0x3, 0x3, 0x2, 0x2, 0xf, 0x12, 0xf, 0xf, 0x12, 0xf, 0xf, 0xf}, ColumnMeta:[]uint16{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2d, 0x0, 0x180, 0x180, 0x0, 0x180, 0x180, 0x2fd}, NullBitmap:[]uint8{0xba, 0x3f}},
		0x3045a:  &TableMapEvent{tableIDSize:6, TableID:0x3045a, Flags:0x1, Schema:[]uint8{0x73, 0x65, 0x69, 0x75, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72}, Table:[]uint8{0x63, 0x6f, 0x6e, 0x73}, ColumnCount:0x1e, ColumnType:[]uint8{0x3, 0x3, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xfe, 0x12, 0xf, 0xf, 0xf, 0xf6, 0xf, 0xf, 0xf, 0xf, 0x1, 0x1, 0x1, 0x12, 0xf, 0xf, 0x12, 0xf, 0xf, 0x3, 0xf, 0x1}, ColumnMeta:[]uint16{0x0, 0x0, 0x30, 0x180, 0x180, 0x180, 0x30, 0xc0, 0xfe03, 0x0, 0x180, 0x180, 0x180, 0xc02, 0x180, 0x180, 0x180, 0x180, 0x0, 0x0, 0x0, 0x0, 0x180, 0x180, 0x0, 0x180, 0x180, 0x0, 0x2fd, 0x0}, NullBitmap:[]uint8{0xfc, 0xff, 0xe3, 0x37}},
		0x3045f:  &TableMapEvent{tableIDSize:6, TableID:0x3045f, Flags:0x1, Schema:[]uint8{0x73, 0x65, 0x69, 0x75, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72}, Table:[]uint8{0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x72}, ColumnCount:0x19, ColumnType:[]uint8{0x3, 0x3, 0x3, 0x1, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xf, 0xfe, 0x3, 0xc, 0x1, 0xc, 0xf, 0xf, 0xc, 0xf, 0xf, 0x3, 0xf, 0x4, 0x4}, ColumnMeta:[]uint16{0x0, 0x0, 0x0, 0x0, 0x2fd, 0x2fd, 0x2fd, 0xc0, 0x12c, 0x30, 0xc, 0xfe06, 0x0, 0x0, 0x0, 0x0, 0x180, 0x180, 0x0, 0x180, 0x180, 0x0, 0x2fd, 0x4, 0x4}, NullBitmap:[]uint8{0xf0, 0xef, 0x5f, 0x0}},
		0x3065f:  &TableMapEvent{tableIDSize:6, TableID:0x3065f, Flags:0x1, Schema:[]uint8{0x73, 0x65, 0x69, 0x75, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72}, Table:[]uint8{0x63, 0x6f, 0x6e, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x6f, 0x75, 0x74, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72}, ColumnCount:0xd, ColumnType:[]uint8{0x3, 0x3, 0x3, 0x3, 0x1, 0x12, 0xf, 0xf, 0x12, 0xf, 0xf, 0x3, 0xf}, ColumnMeta:[]uint16{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x180, 0x180, 0x0, 0x180, 0x180, 0x0, 0x2fd}, NullBitmap:[]uint8{0xe0, 0x17}},
	}

	_, err := parser.parse([]byte{
		/* 0x00, */ 0xc1, 0x86, 0x8e, 0x55, 0x1e, 0xa5, 0x14, 0x80, 0xa, 0x55, 0x0, 0x0, 0x0, 0x7, 0xc,
		0xbf, 0xe, 0x0, 0x0, 0x5f, 0x6, 0x3, 0x0, 0x0, 0x0, 0x1, 0x0, 0x2, 0x0, 0xd, 0xff,
		0x0, 0x0, 0x19, 0x63, 0x7, 0x0, 0xca, 0x61, 0x5, 0x0, 0x5e, 0xf7, 0xc, 0x0, 0xf5, 0x7,
		0x0, 0x0, 0x1, 0x99, 0x96, 0x76, 0x74, 0xdd, 0x10, 0x0, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70,
		0x5f, 0x64, 0x62, 0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6, 0x0, 0x73, 0x79, 0x73, 0x74,
		0x65, 0x6d, 0xb1, 0x3c, 0x38, 0xcb,
	})
	
	if err != nil {
		t.Errorf("error: %+v", err)
	}
}
```

And the test output:
```
=== RUN TestIndexOutOfRange
--- FAIL: TestIndexOutOfRange (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 5 [running]:
testing.func·006()
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:441 +0x181
github.com/siddontang/go-mysql/replication.(*RowsEvent).decodeRows(0xc208090140, 0xc208052320, 0x31, 0x35, 0xc2080900a0, 0xc20805231e, 0x2, 0x37, 0xc208090140, 0x0, ...)
	/tmp/gopathtmp/src/github.com/siddontang/go-mysql/replication/row_event.go:292 +0x60c
github.com/siddontang/go-mysql/replication.(*RowsEvent).Decode(0xc208090140, 0xc208052313, 0x3e, 0x42, 0x0, 0x0)
	/tmp/gopathtmp/src/github.com/siddontang/go-mysql/replication/row_event.go:261 +0x6a6
github.com/siddontang/go-mysql/replication.(*BinlogParser).parseEvent(0xc20801e260, 0xc20801e400, 0xc208052313, 0x3e, 0x42, 0x0, 0x0, 0x0, 0x0)
	/tmp/gopathtmp/src/github.com/siddontang/go-mysql/replication/parser.go:188 +0x12f
github.com/siddontang/go-mysql/replication.(*BinlogParser).parse(0xc20801e260, 0xc208052313, 0x42, 0x42, 0x0, 0x0, 0x0)
	/tmp/gopathtmp/src/github.com/siddontang/go-mysql/replication/parser.go:223 +0x33b
github.com/siddontang/go-mysql/replication.TestIndexOutOfRange(0xc20808e000)
	/tmp/gopathtmp/src/github.com/siddontang/go-mysql/replication/parser_test.go:42 +0x2434
testing.tRunner(0xc20808e000, 0x4350a0)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:555 +0xa8b
```

**Comment by siddontang** [comment]
Thanks @blalor 

I will check it ASAP. :-)

**Comment by blalor** [comment]
Thank you! It's a reproducible problem from a particular log file and position. I can't really share the data, but I can try to isolate specific events if necessary.

**Comment by siddontang** [comment]
Hi @blalor 

My fault. You can see the python version I wrote before [here](https://github.com/noplay/python-mysql-replication/blob/master/pymysqlreplication/row_event.py#L83)

I must check column null first, and I did it in python, but forgot to fix it in go version, :sweat: 

I have updated code, you can checkout and help me test it again.

Thank you very much!

**Comment by blalor** [comment]
Looks good!  Thank you!
