### ISSUE TITLE
Segmentation fault when using offset in binlog parser

### ISSUE THREAD

**Issue by maxbeutel** [siddontang/go-mysql#127]
Hi! I'm experimenting with the binlog parser and used it for some binlog files I from a test db. When using the parser together with an offset that passes by a table map event, I can get a segmentation fault:

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xd963d]

goroutine 10 [running]:
panic(0x22bac0, 0xc4200100f0)
	/usr/local/Cellar/go@1.7/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42008c6c0)
	/usr/local/Cellar/go@1.7/1.7.5/libexec/src/testing/testing.go:579 +0x25d
panic(0x22bac0, 0xc4200100f0)
	/usr/local/Cellar/go@1.7/1.7.5/libexec/src/runtime/panic.go:458 +0x243
github.com/siddontang/go-mysql/replication.(*BinlogParser).parseEvent(0xc42004be40, 0xc42000daa0, 0xc420127200, 0x24, 0x600, 0x24, 0x0, 0x0, 0x0)
	/Users/max/Documents/.../binlog-parser/_vendor/src/github.com/siddontang/go-mysql/replication/parser.go:155 +0x4ed
github.com/siddontang/go-mysql/replication.(*BinlogParser).parseReader(0xc42004be40, 0x379fc0, 0xc42002e2c0, 0xc42000d980, 0x0, 0x0)
	/Users/max/Documents/.../binlog-parser/_vendor/src/github.com/siddontang/go-mysql/replication/parser.go:103 +0x25f
github.com/siddontang/go-mysql/replication.(*BinlogParser).ParseFile(0xc42004be40, 0x2719dd, 0x19, 0x1ac, 0xc42000d980, 0x0, 0x0)
	/Users/max/Documents/.../binlog-parser/_vendor/src/github.com/siddontang/go-mysql/replication/parser.go:59 +0x398

See the attached binlog that produces the issue, **with offset being 429**

[mysql-bin.000005.zip](https://github.com/siddontang/go-mysql/files/918788/mysql-bin.000005.zip)

**Comment by siddontang** [comment]
Hi @maxbeutel 

This is caused that we don't parse the first FormatDescriptionEvent. So if we begin to parse the binlog file with a offset, we must first parse the FormatDescriptionEvent at first, then use the offset.

**Comment by siddontang** [comment]
I will think how to fix it later.

Btw, it is very appreciated that you can send me a PR to fix too.

**Comment by maxbeutel** [comment]
Can I ask you what is the purpose of the offset? Is it the actual byte offset inside the binlog file? I first thought it's the offset of the event, but that is nit the case.

**Comment by siddontang** [comment]
Hi @maxbeutel 

At first, I wanted to let the binlog parser work like mysqlbinlog, the parser may support start position (the byte offset), or start timestamp. 

But I have no time to support it, so now the offset is needless because we only support parsing the binlog from start.

**Comment by maxbeutel** [comment]
@siddontang  I see. Do you think it would be ok to remove the offset then? I think I could work on a PR for that, if you are ok with it to merge.

**Comment by siddontang** [comment]
@maxbeutel  welcome :-)

**Comment by marlonfan** [comment]
this issue need close? @siddontang
