### ISSUE TITLE
求教!!

### ISSUE THREAD

**Issue by always-waiting** [siddontang/go-mysql#304]
```
package main

import (
	"context"
	"fmt"
	"github.com/siddontang/go-mysql/mysql"
	"github.com/siddontang/go-mysql/replication"
	//"reflect"
	//"os"
)

func main() {
	fmt.Println("vim-go")

	// Create a binlog syncer with a unique server id, the server id must be different from other MySQL's.
	// flavor is mysql or mariadb
	cfg := replication.BinlogSyncerConfig{
		ServerID: 100,
		Flavor:   "mysql",
		Host:     "127.0.0.1",
		Port:     3306,
		User:     "root",
		Password: "abc123",
	}
	syncer := replication.NewBinlogSyncer(cfg)

	// Start sync with specified binlog file and position
	streamer, err := syncer.StartSync(mysql.Position{"mysql-bin.000050", 2102})
	if err != nil {
		panic(err)
	}

	for {
		fmt.Println("start get event")
		ev, err := streamer.GetEvent(context.Background())
		fmt.Println("end get event")
		if err != nil {
			panic(err)
		}
		// Dump event
		fmt.Println(ev.Header.EventType)
		//fmt.Println(ev)
		//ev.Dump(os.Stdout)
		//fmt.Println(ev.Header.EventType)
		//ev.Event.Decode(ev.RawData)
	}
}

```

请问，我们发现有很多event,但是`GetEvent` 返回的是BinlogEvent结构，我们要如何能够把它转成其他event呢？例如TableMapEvent

PS:尝试过用如下方式做
```
var mev replication.TableMapEvent
if ev.Header.EventType.String() == "TableMapEvent" {
    mev.Decode(ev.RawData)
}
```
来做尝试，但是报告了如下错误
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/siddontang/go-mysql/replication.(*TableMapEvent).Decode(0xc420051e28, 0xc420105801, 0x32, 0x5ff, 0x0, 0x0)
	/home/test/gocode/src/github.com/siddontang/go-mysql/replication/row_event.go:57 +0x5a1
main.main()
	/home/test/gocode/src/study/binlog/main.go:44 +0x38a
exit status 2

```

请问，我们要如何解决？
谢谢！

**Comment by siddontang** [comment]
use ev.Event directly to convert to the special event.

**Comment by always-waiting** [comment]
@siddontang 
```
if ev.Header.EventType.String() == "TableMapEvent" {
       fmt.Println(ev.Event.Table)
}
```

报错
```
./main.go:44:24: ev.Event.Table undefined (type replication.Event has no field or method Table)
```

**Comment by siddontang** [comment]
```go
e, ok := ev.Event.(*TableMapEvent)
// check ok
```

**Comment by always-waiting** [comment]
THX, ORZ
