### ISSUE TITLE
invalid memory address or nil pointer dereference when try to check the VARIABLES LIKE BINLOG_CHECKSUM

### ISSUE THREAD

**Issue by wanyaxing** [siddontang/go-mysql#483]
https://github.com/siddontang/go-mysql/blob/7a62847fcdb5f46399ad0bc58cccca4a0f7fbb0d/replication/binlogsyncer.go#L253

I Used the maxscale as binlog server, and the server do not support the command "SHOW GLOBAL VARIABLES LIKE ‘BINLOG_CHECKSUM’" , so, the application crashed here at line 253.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x60c9d6]

goroutine 53 [running]:
github.com/siddontang/go-mysql/mysql.(*Resultset).GetValue(0x0, 0x0, 0x1, 0xc0000b6b40, 0x1735b6f, 0x2c, 0xc000238940)
	/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191009015310-f66c8b344478/mysql/resultset.go:238 +0x26
github.com/siddontang/go-mysql/mysql.(*Resultset).GetString(0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0xc000238940)
	/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191009015310-f66c8b344478/mysql/resultset.go:401 +0x4c
github.com/siddontang/go-mysql/replication.(*BinlogSyncer).registerSlave(0xc00003a2c0, 0xc000438c00, 0xc00008c218)
	/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191009015310-f66c8b344478/replication/binlogsyncer.go:253 +0x164
github.com/siddontang/go-mysql/replication.(*BinlogSyncer).prepare(0xc00003a2c0, 0x2, 0xc000496090)
	/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191009015310-f66c8b344478/replication/binlogsyncer.go:331 +0x89
github.com/siddontang/go-mysql/replication.(*BinlogSyncer).prepareSyncPos(0xc00003a2c0, 0x0, 0x0, 0x4, 0x1, 0x2)
	/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191009015310-f66c8b344478/replication/binlogsyncer.go:602 +0x2f
github.com/siddontang/go-mysql/replication.(*BinlogSyncer).StartSync(0xc00003a2c0, 0x0, 0x0, 0x4, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20191009015310-f66c8b344478/replication/binlogsyncer.go:368 +0x1c5
github.com/pingcap/dm/pkg/binlog/reader.(*TCPReader).StartSyncByPos(0xc0004361e0, 0x0, 0x0, 0xc000000004, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/pkg/binlog/reader/tcp.go:77 +0x1db
github.com/pingcap/dm/relay/reader.(*reader).setUpReaderByPos(0xc00038fc20, 0x0, 0x2)
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/relay/reader/reader.go:166 +0x30c
github.com/pingcap/dm/relay/reader.(*reader).Start(0xc00038fc20, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/relay/reader/reader.go:111 +0x231
github.com/pingcap/dm/relay.(*Relay).setUpReader(0xc00049c000, 0xc0004c6a80, 0x0, 0x0, 0x5)
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/relay/relay.go:606 +0x2ae
github.com/pingcap/dm/relay.(*Relay).process(0xc00049c000, 0x195e980, 0xc0004620c0, 0x0, 0x0)
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/relay/relay.go:256 +0x15d
github.com/pingcap/dm/relay.(*Relay).Process(0xc00049c000, 0x195e980, 0xc0004620c0, 0xc00008d500)
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/relay/relay.go:191 +0x89
github.com/pingcap/dm/dm/worker.(*realRelayHolder).run(0xc000218c40)
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/dm/worker/relay.go:167 +0x10a
github.com/pingcap/dm/dm/worker.(*realRelayHolder).Start.func1(0xc000218c40)
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/dm/worker/relay.go:143 +0x61
created by github.com/pingcap/dm/dm/worker.(*realRelayHolder).Start
	/home/jenkins/agent/workspace/build_dm_master/go/src/github.com/pingcap/dm/dm/worker/relay.go:141 +0x5c

```

**Comment by siddontang** [comment]
I guess one fast way to fix it is to check whether r is nil, but here I am surprised that maxscale doesn't support this. 

if r is nil, you may explicitly set None like https://github.com/siddontang/go-mysql/blob/7a62847fcdb5f46399ad0bc58cccca4a0f7fbb0d/replication/binlogsyncer.go#L263

do you want to have a try to fix it?

**Comment by wanyaxing** [comment]
the r is not nil, the log is printed as below:

`&{Status:2 InsertId:0 AffectedRows:0 Resultset:<nil>}`

**Comment by siddontang** [comment]
Got it, you can use `r.RowNumber() == 0` to check at first and use `r.GetString()` to check again. If RowNumbr is 0 or no checksum string, we need to set the checksum to None explicitly. 

Can you help us add this, I think it is very easy.

**Comment by wanyaxing** [comment]
there is no `RowNumber` in `r`, crash again.

![image](https://user-images.githubusercontent.com/7940795/76734700-7134c980-679e-11ea-9ded-79ececaf353f.png)

![image](https://user-images.githubusercontent.com/7940795/76734738-7e51b880-679e-11ea-8d7e-7069a5dad796.png)

I uesd `r != nil && r.Resultset != nil` to check it, and it works.

![image](https://user-images.githubusercontent.com/7940795/76734850-bd800980-679e-11ea-9373-1432cfcc22ed.png)


I had push a PR for this bug, https://github.com/siddontang/go-mysql/pull/486 .
