### ISSUE TITLE
replication block when network down

### ISSUE THREAD

**Issue by iampastor** [siddontang/go-mysql#82]
when the network is down (such as unplug the network cable) and recover after, the replication client will block at ReadPacket, this is the info of pprof:
```
goroutine 19 [IO wait, 14 minutes]:
net.runtime_pollWait(0x7fe48c176b70, 0x72, 0xc82177e000)
	/home/cdyf/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82176a760, 0x72, 0x0, 0x0)
	/home/cdyf/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82176a760, 0x0, 0x0)
	/home/cdyf/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82176a700, 0xc82177e000, 0x1000, 0x1000, 0x0, 0x7fe48c171050, 0xc82000a0f8)
	/home/cdyf/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc821768120, 0xc82177e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/cdyf/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8217783c0)
	/home/cdyf/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8217783c0, 0xc821c66148, 0x4, 0x4, 0x8, 0x0, 0x0)
	/home/cdyf/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fe48c131078, 0xc8217783c0, 0xc821c66148, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
	/home/cdyf/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fe48c131078, 0xc8217783c0, 0xc821c66148, 0x4, 0x4, 0x20, 0x0, 0x0)
	/home/cdyf/go/src/io/io.go:315 +0x62
mysql_byroad/vendor/github.com/siddontang/go-mysql/packet.(*Conn).ReadPacketTo(0xc82101e8c0, 0x7fe48c175d78, 0xc821a388c0, 0x0, 0x0)
	/home/cdyf/goworkspace/src/mysql_byroad/vendor/github.com/siddontang/go-mysql/packet/conn.go:81 +0xf1
mysql_byroad/vendor/github.com/siddontang/go-mysql/packet.(*Conn).ReadPacket(0xc82101e8c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/cdyf/goworkspace/src/mysql_byroad/vendor/github.com/siddontang/go-mysql/packet/conn.go:35 +0x92
mysql_byroad/vendor/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).onStream(0xc821717480, 0xc82101eca0)
	/home/cdyf/goworkspace/src/mysql_byroad/vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go:479 +0xa8
created by mysql_byroad/vendor/github.com/siddontang/go-mysql/replication.(*BinlogSyncer).startDumpStream
	/home/cdyf/goworkspace/src/mysql_byroad/vendor/github.com/siddontang/go-mysql/replication/binlogsyncer.go:220 +0x111
```
I think this is because mysql server closed the connection and replication client didn't receive any close data because of bad network, so it blocked at reading data from this connection. Is there any solution for this condition?

**Comment by siddontang** [comment]
Hi @iampastor 

I think we can add a read timeout here. But if the connection is good and we don't receive any binlog from MySQL after the timeout, the connection will be closed too and go-mysql will reconnect it. 
Another way is to update the TCP heartbeat interval parameters with sysctrl.

**Comment by iampastor** [comment]
@siddontang ye, this is what I did, adding a read timeout, but I think this is not a very good solution, Does mysql replication have any heart beat message or other keep alive mechanism so that we can check whether the connection is bad?

**Comment by siddontang** [comment]
@iampastor 
MySQL replication has no heartbeat message, so I don't think other ways.

**Comment by iampastor** [comment]
@siddontang 
ok, I see. thanks a lot. I will use time out to check the connection.

**Comment by siddontang** [comment]
Thanks @iampastor 
You can send me a PR.

**Comment by 3manuek** [comment]
@iampastor You can keep the coordinates, retry the connection after timeout and set a limit to the loop. 

@siddontang I see that you can enable heartbeat by using semi-sync through [Slave_heartbeat_period](https://dev.mysql.com/doc/refman/5.5/en/server-status-variables.html#statvar_Slave_heartbeat_period), don't know how the underlying protocol works tho :( .

**Comment by siddontang** [comment]
Hi @3manuek , I don't find any protocol document on how to support `Slave_heartbeat_period` :sob:

**Comment by 3manuek** [comment]
Yeah, the only entry on the docs is [this one](https://dev.mysql.com/doc/internals/en/heartbeat-event.html). So, I dug into the [Binlog_sender::send_heartbeat_event at sql/rpl_binlog_sender.cc](https://github.com/mysql/mysql-server/blob/71f48ab393bce80a59e5a2e498cd1f46f6b43f9a/sql/rpl_binlog_sender.cc#L1102-L1133) and I see that it is just an "empty" event (it only has the checksum if enabled).

But mostly it just sets the header and nothing more:
```
 /* Timestamp field */
  int4store(header, 0);
  header[EVENT_TYPE_OFFSET] = binary_log::HEARTBEAT_LOG_EVENT;
  int4store(header + SERVER_ID_OFFSET, server_id);
  int4store(header + EVENT_LEN_OFFSET, event_len);
  int4store(header + LOG_POS_OFFSET, static_cast<uint32>(log_pos));
  int2store(header + FLAGS_OFFSET, 0);
```

So dealing with it shouldn't be more issue as it is a generic event  \o/

The tricky part I guess will be how to deal with the timeout tho. The `MASTER_HEARTBEAT_PERIOD` can be set at `replication.BinlogSyncerConfig`, but a timer should be set at the beginning of the streamer and reset on each heartbeat event. Seems like it can be handled manually outside the library by just providing the necessary interface to handle the event (it can be up to the user on how to  deal with it).

**Comment by siddontang** [comment]
Hi @3manuek 

The HEARTBEAT_EVENT is sent by the master periodically. We can add `MASTER_HEARTBEAT_PERIOD` configuration.
If set (>0, maybe should better > the time configured in MySQL), we will set read timeout for the connection, and we will retry after the connection is closed.

**Comment by picago** [comment]
just use "SELECT 'x'" to keep the coordinates?

**Comment by lkpjj** [comment]
if client.conn is closed periodically，connection maybe not close on master.

**Comment by siddontang** [comment]
Hi @lkpjj 

Can mysql keepalive not close the tombstone connection? Seem this is the problem for all client connections.

**Comment by iyidan** [comment]
How about TCP keepAlive ?

Like this:
1. Add a extra function with a tcp-keep-alive paramter in package client/conn.go
`func ConnectWithKeepAlive(keepd time.Duration) {
    // ...
    // ... same as Connect() method

    conn, err := net.DialTimeout(proto, addr, 10*time.Second)
    if err != nil {
        return nil, errors.Trace(err)
    }

    if tcpConn, ok :=conn.(*net.TCPConn); ok && keepd > 0 {
        err = tcpConn.SetKeepAlive(true)
        if err != nil {
            return nil, errors.Trace(err)
        }
        err = tcpConn.SetKeepAlivePeriod(keepd)
        if err != nil {
            return nil, errors.Trace(err)
        }
    }

    c.Conn = packet.NewConn(conn)

    // ... same as Connect() method
    // ...
}`

2. And then use it in package replication/binlogsyncer.go?
(maybe add a option into the BinlogSyncerConfig struct)

**Comment by iyidan** [comment]
How about TCP keepAlive ?

Like this:

Add a extra function with a tcp-keep-alive paramter in package _client/conn.go_
```
func ConnectWithKeepAlive(keepd time.Duration) {
// ...
// ... same as Connect() method

conn, err := net.DialTimeout(proto, addr, 10*time.Second)
if err != nil {
return nil, errors.Trace(err)
}

if tcpConn, ok :=conn.(*net.TCPConn); ok && keepd > 0 {
err = tcpConn.SetKeepAlive(true)
if err != nil {
return nil, errors.Trace(err)
}
err = tcpConn.SetKeepAlivePeriod(keepd)
if err != nil {
return nil, errors.Trace(err)
}
}

c.Conn = packet.NewConn(conn)

// ... same as Connect() method
// ...
}
```

And then use it in package _replication/binlogsyncer.go_?
(maybe add a option into the BinlogSyncerConfig struct)

**Comment by siddontang** [comment]
@iyidan 

We can't do it directly, in some cases, MySQL will not send any events but we can't close the connection. 

https://github.com/siddontang/go-mysql/issues/82#issuecomment-257067473 may work but I have no time to verify it now yet.

**Comment by iyidan** [comment]
@siddontang 
I mean, use TCP‘s KeepAlive feature (layer 4) to deal with the _**unplug the network cable**_ situation.
Even if mysql no event to send, tcp will keep the heartbeat between client and server.

So, the connection will not closed until the server crashed or tcp loss the FIN segment.

**Comment by siddontang** [comment]
Hi @iyidan 

There may be another problem if we close the connection explicitly, see https://github.com/alibaba/canal/issues/139

**Comment by iyidan** [comment]
I tested in my local machine， mysql server does not close **_the binlog dump connection_** even if the underlying tcp connection is lost(or in close_wait state).
until there is a new event to be send, mysql will check and clean the bad connections
Seemingly no good solution for this

**Comment by svaroqui** [comment]
Hi Thanks for the siddon galaxy tools, 

The replication protocol as been fully describe here 
https://mariadb.com/kb/en/library/replication-protocol/

/Svar
